--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.391.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 08/10/2020 21:46:16
-- Server version: 10.4.10
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS ichefdb;

CREATE DATABASE ichefdb
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE ichefdb;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  usu_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  usu_nome varchar(200) NOT NULL DEFAULT '',
  usu_login varchar(100) NOT NULL DEFAULT '',
  usu_senha varchar(255) NOT NULL DEFAULT '',
  usu_tipo enum ('Cliente', 'Administrador') NOT NULL DEFAULT 'Cliente',
  usu_data_nascimento date NOT NULL,
  usu_data_cadastro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (usu_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_usu_login` on table `usuarios`
--
ALTER TABLE usuarios
ADD UNIQUE INDEX UK_usu_login (usu_login);

--
-- Create table `usuarios_enderecos`
--
CREATE TABLE usuarios_enderecos (
  end_id int(11) UNSIGNED NOT NULL,
  end_id_usuario int(11) UNSIGNED NOT NULL,
  end_apelido varchar(50) NOT NULL DEFAULT 'Outro',
  end_logradouro varchar(300) NOT NULL DEFAULT '',
  end_numero varchar(50) NOT NULL DEFAULT 's/n',
  end_complemento varchar(200) DEFAULT NULL,
  end_cep varchar(10) NOT NULL DEFAULT '',
  end_cidade varchar(100) NOT NULL DEFAULT '',
  end_estado varchar(100) NOT NULL DEFAULT '',
  end_data_cadastro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (end_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE usuarios_enderecos
ADD CONSTRAINT FK_endereco_usuario FOREIGN KEY (end_id_usuario)
REFERENCES usuarios (usu_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `vendas`
--
CREATE TABLE vendas (
  ven_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ven_id_endereco_usuario int(11) UNSIGNED NOT NULL,
  ven_pagamento_realizado tinyint(1) NOT NULL DEFAULT 0,
  ven_data_venda datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  ven_data_pagamento datetime DEFAULT NULL,
  PRIMARY KEY (ven_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE vendas
ADD CONSTRAINT FK_endereco_venda FOREIGN KEY (ven_id_endereco_usuario)
REFERENCES usuarios_enderecos (end_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `receitas_categorias`
--
CREATE TABLE receitas_categorias (
  cat_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  cat_nome varchar(100) NOT NULL DEFAULT '',
  cat_vegano tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (cat_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 10922,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_categoria_nome` on table `receitas_categorias`
--
ALTER TABLE receitas_categorias
ADD UNIQUE INDEX UK_categoria_nome (cat_nome);

--
-- Create table `receitas`
--
CREATE TABLE receitas (
  rec_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  rec_nome varchar(200) NOT NULL DEFAULT '',
  rec_id_categoria int(11) UNSIGNED NOT NULL,
  rec_preco float UNSIGNED NOT NULL DEFAULT 0,
  rec_receita_txt text DEFAULT NULL,
  rec_link_youtube varchar(500) DEFAULT NULL,
  rec_data_cadastro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  rec_usuario_cadastro int(11) UNSIGNED NOT NULL,
  PRIMARY KEY (rec_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_receita_nome` on table `receitas`
--
ALTER TABLE receitas
ADD UNIQUE INDEX UK_receita_nome (rec_nome);

--
-- Create foreign key
--
ALTER TABLE receitas
ADD CONSTRAINT FK_categoria_receita FOREIGN KEY (rec_id_categoria)
REFERENCES receitas_categorias (cat_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE receitas
ADD CONSTRAINT FK_usuario_receita FOREIGN KEY (rec_usuario_cadastro)
REFERENCES usuarios (usu_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `vendas_relacao`
--
CREATE TABLE vendas_relacao (
  vr_id_venda int(11) UNSIGNED NOT NULL,
  vr_id_receita int(11) UNSIGNED NOT NULL,
  vr_quantidade_receita int(11) UNSIGNED NOT NULL DEFAULT 1
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_vendas_receita_relacao` on table `vendas_relacao`
--
ALTER TABLE vendas_relacao
ADD UNIQUE INDEX UK_vendas_receita_relacao (vr_id_venda, vr_id_receita);

--
-- Create foreign key
--
ALTER TABLE vendas_relacao
ADD CONSTRAINT FK_relacao_receita FOREIGN KEY (vr_id_venda)
REFERENCES vendas (ven_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE vendas_relacao
ADD CONSTRAINT FK_relacao_venda FOREIGN KEY (vr_id_receita)
REFERENCES receitas (rec_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `ingredientes_unidades`
--
CREATE TABLE ingredientes_unidades (
  iun_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  iun_unidade_sigla varchar(30) NOT NULL DEFAULT '',
  iun_nome_singular varchar(100) NOT NULL DEFAULT '',
  ium_nome_plural varchar(100) NOT NULL DEFAULT '',
  iun_descricao varchar(500) DEFAULT NULL,
  PRIMARY KEY (iun_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_ingredientes_unidades_iun_unidade_sigla` on table `ingredientes_unidades`
--
ALTER TABLE ingredientes_unidades
ADD UNIQUE INDEX UK_ingredientes_unidades_iun_unidade_sigla (iun_unidade_sigla);

--
-- Create table `ingredientes`
--
CREATE TABLE ingredientes (
  ing_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ing_nome varchar(200) NOT NULL DEFAULT '',
  ing_unidade_padrao int(11) UNSIGNED NOT NULL,
  ing_data_cadastro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  ing_ativo tinyint(1) NOT NULL DEFAULT 1,
  ing_custo float NOT NULL DEFAULT 0,
  PRIMARY KEY (ing_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE ingredientes
ADD CONSTRAINT FK_unidade_padrao FOREIGN KEY (ing_unidade_padrao)
REFERENCES ingredientes_unidades (iun_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `ingredientes_receita`
--
CREATE TABLE ingredientes_receita (
  inr_id_receita int(11) UNSIGNED NOT NULL,
  inr_id_ingrediente int(11) UNSIGNED NOT NULL,
  inr_quantidade float UNSIGNED NOT NULL,
  inr_id_unidade int(11) UNSIGNED NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_ingredientes_receita` on table `ingredientes_receita`
--
ALTER TABLE ingredientes_receita
ADD UNIQUE INDEX UK_ingredientes_receita (inr_id_receita, inr_id_ingrediente);

--
-- Create foreign key
--
ALTER TABLE ingredientes_receita
ADD CONSTRAINT FK_ingrediente_receita FOREIGN KEY (inr_id_receita)
REFERENCES receitas (rec_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE ingredientes_receita
ADD CONSTRAINT FK_receita_ingrediente FOREIGN KEY (inr_id_ingrediente)
REFERENCES ingredientes (ing_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE ingredientes_receita
ADD CONSTRAINT FK_unidade_ingrediente FOREIGN KEY (inr_id_ingrediente)
REFERENCES ingredientes_unidades (iun_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'iChef Admin', 'admin', '***(segredo!)***', 'Administrador', '0000-00-00', '2020-09-22 11:52:24'),
(2, 'Primeiro usuário', 'user', '***(segredoTb!)***', 'Cliente', '0000-00-00', '2020-09-22 11:52:52');

-- 
-- Dumping data for table usuarios_enderecos
--
-- Table ichefdb.usuarios_enderecos does not contain any data (it is empty)

-- 
-- Dumping data for table receitas_categorias
--
INSERT INTO receitas_categorias VALUES
(1, 'Brasileira', 0),
(2, 'Asiática', 0),
(3, 'Vegana', 1);

-- 
-- Dumping data for table vendas
--
-- Table ichefdb.vendas does not contain any data (it is empty)

-- 
-- Dumping data for table receitas
--
INSERT INTO receitas VALUES
(1, 'Filé Wellington', 1, 0, NULL, NULL, '2020-09-22 11:53:14', 1),
(2, 'Filé à parmegiana', 1, 0, NULL, NULL, '2020-09-22 11:54:20', 1);

-- 
-- Dumping data for table ingredientes_unidades
--
INSERT INTO ingredientes_unidades VALUES
(1, 'un.', 'unidade', 'unidades', 'Unidade'),
(2, 'kg', 'quilograma', 'quilogramas', 'Quilograma'),
(3, 'g', 'grama', 'gramas', 'Grama'),
(4, 'c.s.', 'colher de sopa', 'colheres de sopa', 'Colher de sopa'),
(5, 'c.c.', 'colher de chá', 'colheres de chá', 'Colher de chá'),
(6, 'xic', 'xícara de chá', 'xícaras de chá', 'Xícara de xá'),
(7, 'xcf', 'xícara de café', 'xícaras de café', 'Xíxara de café');

-- 
-- Dumping data for table ingredientes
--
-- Table ichefdb.ingredientes does not contain any data (it is empty)

-- 
-- Dumping data for table vendas_relacao
--
-- Table ichefdb.vendas_relacao does not contain any data (it is empty)

-- 
-- Dumping data for table ingredientes_receita
--
-- Table ichefdb.ingredientes_receita does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;